
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 23;
  public static final int AND = 12;
  public static final int LT = 4;
  public static final int SQUARE = 8;
  public static final int AGENTLT = 5;
  public static final int RPAREN = 21;
  public static final int OR = 13;
  public static final int LBRACK = 22;
  public static final int NOT = 9;
  public static final int IDENTIFIER = 24;
  public static final int TRUE = 14;
  public static final int EVENTUALLY = 17;
  public static final int IMPLIES = 11;
  public static final int LPAREN = 20;
  public static final int COLON = 7;
  public static final int EOF = 0;
  public static final int ALWAYS = 16;
  public static final int FALSE = 15;
  public static final int MINUS = 2;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int IFF = 10;
  public static final int UNTIL = 19;
  public static final int EQ = 6;
  public static final int NEXT = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MINUS",
  "DOT",
  "LT",
  "AGENTLT",
  "EQ",
  "COLON",
  "SQUARE",
  "NOT",
  "IFF",
  "IMPLIES",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "ALWAYS",
  "EVENTUALLY",
  "NEXT",
  "UNTIL",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "IDENTIFIER"
  };
}

