
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package claimlang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tFORMULA = 28;
  public static final int tAGENTLT = 13;
  public static final int tSTATE = 4;
  public static final int tINITIAL = 5;
  public static final int tPRODUCT = 17;
  public static final int tTRANSITIONSYSTEM = 2;
  public static final int tLT = 12;
  public static final int tLBRACK = 20;
  public static final int tACTIONTRANSITIONSYSTEM = 3;
  public static final int tSATISFIES = 25;
  public static final int tVALID = 26;
  public static final int tLPAREN = 18;
  public static final int tRBRACK = 21;
  public static final int tSEMICOLON = 16;
  public static final int tLCURLY = 22;
  public static final int EOF = 0;
  public static final int tEVENT = 8;
  public static final int tTRUSTORDER = 7;
  public static final int tCOLON = 15;
  public static final int tRPAREN = 19;
  public static final int tSATISFIABLE = 24;
  public static final int tCHECK = 27;
  public static final int error = 1;
  public static final int tRCURLY = 23;
  public static final int tFORMULALITERAL = 30;
  public static final int tEQ = 14;
  public static final int tTIMEORDER = 6;
  public static final int tMINUS = 10;
  public static final int tIDENTIFIER = 29;
  public static final int tARROW = 9;
  public static final int tDOT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tTRANSITIONSYSTEM",
  "tACTIONTRANSITIONSYSTEM",
  "tSTATE",
  "tINITIAL",
  "tTIMEORDER",
  "tTRUSTORDER",
  "tEVENT",
  "tARROW",
  "tMINUS",
  "tDOT",
  "tLT",
  "tAGENTLT",
  "tEQ",
  "tCOLON",
  "tSEMICOLON",
  "tPRODUCT",
  "tLPAREN",
  "tRPAREN",
  "tLBRACK",
  "tRBRACK",
  "tLCURLY",
  "tRCURLY",
  "tSATISFIABLE",
  "tSATISFIES",
  "tVALID",
  "tCHECK",
  "tFORMULA",
  "tIDENTIFIER",
  "tFORMULALITERAL"
  };
}

